#test
name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and sign release
      env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS_NAME: ${{ secrets.KEYSTORE_ALIAS_NAME }}
          KEYSTORE_ALIAS_PASS: ${{ secrets.KEYSTORE_ALIAS_PASS }}

      run: |
          chmod +x ./gradlew
          echo "The GitHub Action Secret will be masked:  "
          echo ${{secrets.KEYSTORE_PASSWORD}} | sed 's/./& /g'
          ./gradlew assembleRelease -Pandroid.injected.signing.store.file=upload-keystore.jks \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEYSTORE_ALIAS_NAME \
            -Pandroid.injected.signing.key.password=$KEYSTORE_ALIAS_PASS
