name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
         java-version: '11'
         distribution: 'temurin'
         cache: gradle

      - name: Build and sign release
        env:
          KEYSTORE_PASSWORD: ${{ env.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS_NAME: ${{ env.KEYSTORE_ALIAS_NAME }}
          KEYSTORE_ALIAS_PASS: ${{ env.KEYSTORE_ALIAS_PASS }}
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease -Pandroid.injected.signing.store.file=upload-keystore.jks \
            -Pandroid.injected.signing.store.password="${KEYSTORE_PASSWORD}" \
            -Pandroid.injected.signing.key.alias="${KEYSTORE_ALIAS_NAME}" \
            -Pandroid.injected.signing.key.password="${KEYSTORE_ALIAS_PASS}"

      - name: Echo KEYSTORE_PASSWORD
        run: |
          echo "KEYSTORE_PASSWORD: $KEYSTORE_PASSWORD"
